version: '3'
volumes:
  auth-data:
services:
  # OAuth database server
  auth-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      # Use this option to persist the MySQL DBs in a shared volume.
      #- ./mysqldata:/var/lib/mysql:rw,delegated
      # Use this option to persist the MySQL DBs in a data volume.
      - auth-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Ebtylor1871!"
      MYSQL_ROOT_HOST: "%"
    restart:  always
    labels:
      kompose.volume.size: 1Gi
  # OAuth application server
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: tgwconsulting/tgw-oauth:latest
    entrypoint: ["/opt/tgw/app/lib/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
    links:
      - auth-db
      - auth-cache
    environment:
      RAILS_ENV: development
    restart:  always
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: auth.tgwconsulting.local
  # OAuth cache
  auth-cache:
    image: redis:5.0
    ports:
      - "6379:6379"
