apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: auth-cache
  name: auth-cache
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: auth-cache
    spec:
      containers:
      - image: redis:5.0
        name: auth-cache
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
