apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.expose: auth.tgwconsulting.local
    kompose.service.type: nodeport
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: auth-server
  name: auth-server
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: auth-server
  type: NodePort
status:
  loadBalancer: {}
